// Environment models configuration (tree, plants, rocks, branches)
export const COMMON_MODELS = [
  {
    name: "Boulder",
    path: "/models/common/plant/boulder_01_1k.gltf",
    scale: 0.1,
    position: { x: 0.2, z: 0.7 },
    rotationY: 0.8,
  },
  {
    name: "Plant",
    path: "/models/common/rock/periwinkle_plant_1k.gltf",
    scale: 0.35,
    position: { x: -0.3, z: 0.25 },
    rotationY: -0.5,
  },
  {
    name: "Plant 1",
    path: "/models/common/rock/periwinkle_plant_1k.gltf",
    scale: 0.35,
    position: { x: -0.3, z: 0.25 },
    rotationY: 3,
  },
  {
    name: "Plant 2",
    path: "/models/common/rock/periwinkle_plant_1k.gltf",
    scale: 0.35,
    position: { x: -0.3, z: 0.25 },
    rotationY: -1.5,
  },
  {
    name: "Plant 3",
    path: "/models/common/rock/periwinkle_plant_1k.gltf",
    scale: 0.35,
    position: { x: -0.3, z: 0.25 },
    rotationY: 0.5,
  },
  {
    name: "Island Tree",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.18,
    position: { x: 0.4, z: 0.45 },
    rotationY: 2.2,
  },
  {
    name: "Island Tree 2",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.18,
    position: { x: -0.4, z: -0.45 },
    rotationY: -2,
  },
  {
    name: "small tree",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.1,
    position: { x: 1, z: -0.45 },
    rotationY: 1.2,
  },
  {
    name: "small tree 1",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.1,
    position: { x: 0.2, z: 1.45 },
    rotationY: 5,
  },
  {
    name: "small tree 2",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.1,
    position: { x: -0.2, z: -1.45 },
    rotationY: 5,
  },
  {
    name: "far Tree",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.25,
    position: { x: 0.1, z: -2 },
    rotationY: 1.2,
  },
  {
    name: "far Tree 1",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.25,
    position: { x: 2, z: 2 },
    rotationY: 1.2,
  },
  {
    name: "far Tree 2",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.25,
    position: { x: -2.3, z: 2 },
    rotationY: 1.2,
  },
  {
    name: "far Tree 3",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.25,
    position: { x: -1.3, z: 1.9 },
    rotationY: 1.2,
  },
  {
    name: "far Tree 4",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.25,
    position: { x: -1.8, z: -0.4 },
    rotationY: 1.2,
  },
  {
    name: "far Tree 5",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.25,
    position: { x: 2.3, z: -2.5 },
    rotationY: 1.2,
  },
  {
    name: "far Tree 2-2",
    path: "/models/common/tree/island_tree_02_1k.gltf",
    scale: 0.25,
    position: { x: -2.3, z: -2.3 },
    rotationY: 1.2,
  },
  {
    name: "Dry Branch",
    path: "/models/common/branches/dry_branches_medium_01_1k.gltf",
    subMeshName: "dry_branches_medium_01_b",
    scale: 0.35,
    position: { x: 0.35, z: 0.4 },
    rotationY: 2,
  },
];

// Light beam color presets
export const LIGHT_COLOR_PRESETS = [
  { name: "Warm Yellow", hex: 0xfff3aa },
  { name: "Cyan Ice", hex: 0x00f5ff },
  { name: "Neon Green", hex: 0x10b981 },
  { name: "Electric Purple", hex: 0xa855f7 },
  { name: "Laser Red", hex: 0xef4444 },
  { name: "Pure White", hex: 0xffffff },
];
